# docker-compose.yml
version: '3.7'

services:
  web:
    build: .
    ports:
      - 8765:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=memento
      - POSTGRES_PASSWORD=memento
      - POSTGRES_DB=memento
  adminer:
    image: adminer:latest
    ports:
      - "5678:8080"
    depends_on:
      - db
  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z-cpuv1
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: 123456789
      MINIO_SECRET_KEY: 987654321
    ports:
      - "9991:9001"
      - "9999:9000"
    volumes:
      - ./minio-data:/data
  front:
    build: ../memento_front
    ports:
      - "8776:80"

volumes:
  postgresdb-data: